AWSTemplateFormatVersion: "2010-09-09"
Description: ECS cluster for worker management
Resources:
  BucketLoadBalancerAccessLogs:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub loadbalancer-worker-management-${AWS::Region}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: aws:kms
      Tags:
        - Key: Service
          Value: WorkerManagement
        - Key: Project
          Value: Sputnik
        - Key: Team
          Value: TeamZero:Infra

  BucketLoadBalancerAccessLogsPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketLoadBalancerAccessLogs
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Sid: ELBAccessLogs20130930
          Effect: Allow
          Resource: !Sub arn:aws:s3:::${BucketLoadBalancerAccessLogs}/AWSLogs/${AWS::AccountId}/*
          # https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-access-logs.html#attach-bucket-policy
          Principal:
            AWS: 127311923021
          Action: ['s3:PutObject']

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DependsOn: BucketLoadBalancerAccessLogsPolicy
    Properties:
      Name: ecs-services
      Subnets:
      - !ImportValue SubnetAZ1Public
      - !ImportValue SubnetAZ2Public
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: 'true'
        - Key: access_logs.s3.bucket
          Value: !Ref BucketLoadBalancerAccessLogs

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for loadbalancer to services on ECS
      VpcId: !ImportValue VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1

  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: default
      VpcId: !ImportValue VPC
      Protocol: HTTP
      Port: 80

  WorkerManagementECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: WorkerManagementECSCluster

Outputs:
  LoadBalancerDNS:
    Description: Domain name for the loadbalancer
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: WorkerManagementDomainName
  WorkerManagementECSCluster:
    Description: ECS Cluster
    Value: !Ref WorkerManagementECSCluster
    Export:
      Name: WorkerManagementECSCluster
  WorkerManagementLoadBalancerSG:
    Description: ECS Cluster security groups
    Value: !Ref LoadBalancerSecurityGroup
    Export:
      Name: WorkerManagementECSClusterSG
  LoadBalancerListener:
    Description: LoadBalancer listener
    Value: !Ref LoadBalancerListener
    Export:
      Name: LoadBalancerListener


