AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Service Definition
Resources:
  WorkerManagementTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
      Family: WorkerManagementService
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        -
          Name: WorkerManagementAPI
          Image: 574574226067.dkr.ecr.us-east-1.amazonaws.com/worker-management:latest
          PortMappings:
            -
              ContainerPort: 3000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: worker-management

  WorkerManagementECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue WorkerManagementECSCluster
      DesiredCount: 2
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: WorkerManagementAPI
          ContainerPort: 3000
          TargetGroupArn: !Ref WebTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
          - !ImportValue SubnetAZ1Private
          - !ImportValue SubnetAZ1Private
          SecurityGroups:
            - !ImportValue ContainerSecurityGroup
      ServiceName: WorkerManagement
      TaskDefinition: !Ref WorkerManagementTaskDefinition

  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      TargetType: ip

  WebListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue LoadBalancerListener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values:
            - /worker
      Actions:
        - TargetGroupArn: !Ref WebTargetGroup
          Type: forward
